DragonFeedCode/DragonFeed/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('articles.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DragonFeedCode/articles/urls.py
from django.conf.urls import include, url
from . import views 

app_name = 'article'

urlpatterns = [
    #index view - all events will be viewed here 
    url(r'^$', views.IndexView.as_view(), name="index"),

    #add event - where the user can add events 
    url(r'^formal$', views.FormalEventsView.as_view(), name="formal"),

        #add event - where the user can add events 
    url(r'^informal$', views.InformalEventsView.as_view(), name="informal"),

    #detailed view - where if the user clicks on an event they get more info
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name="details"),

    #add event - where the user can add events 
    url(r'^addevent$', views.AddEvent.as_view(), name="addevent")

]

DragonFeedCode/articles/models.py
from django.db import models
from datetime import datetime
from django.core.urlresolvers import reverse

class Article(models.Model):
    Title = models.CharField(max_length=50)
    Orginization = models.CharField(max_length=50, blank=True)
    Location = models.CharField(max_length=100)
    Description = models.TextField(blank=True)
    Start = models.DateTimeField(default=datetime.now, blank=True)
    End = models.DateTimeField(default=datetime.now, blank=True)
    Link = models.CharField(max_length = 500, blank=True)
    Tag = models.CharField(max_length = 20)
    Flyer = models.FileField()
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def get_absolute_url(self):
      return reverse('article:details', kwargs={'pk': self.pk})
        
    def __str__(self):
	    return self.Title + " - " + self.Orginization

DragonFeedCode/articles/forms.py
from django.forms import ModelForm
from .models import Article

class AddArticle(ModelForm):
    class Meta:
        model = Article
        fields = ['Title', 'Orginization', 'Location', 'Description', 'Start', 'End', 'Tag', 'Link', 'Flyer']

DragonFeedCode/articles/views.py
from .models import Article
from django.views import generic
from django.views.generic import View
from django.views.generic.edit import  CreateView, UpdateView, DeleteView
from django.http import HttpResponse

class IndexView(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'allArticles'

    def get_queryset(self):
        return Article.objects.all()

class FormalEventsView(generic.ListView):
    template_name = 'formalEvents.html'
    context_object_name = 'allArticles'
    
    def get_queryset(self):
        return Article.objects.all()

class InformalEventsView(generic.ListView):
    template_name = 'informalEvents.html'
    context_object_name = 'allArticles'
    
    def get_queryset(self):
        return Article.objects.all()
    
class DetailView(generic.DetailView):
    template_name = 'details.html'
    model = Article

class AddEvent(CreateView):
    model = Article
    fields = '__all__'
    template_name = 'article_form.html'
    fields = ['Title', 'Orginization', 'Location', 'Description', 'Start', 'End', 'Tag', 'Link', 'Flyer']

DragonFeedCode/articles/templates/article_form.html
{% extends 'layout.html'%}
{% load staticfiles %}

{% block title %}
	<title>DragonFeed - Create Event</title>
{% endblock %}

{% block header %}
	<h3>Add New Article</h3>
{% endblock %}

{% block index.html%}
	<div class="container">
		<div class="add-event-form">
				<p class="text-center content-header">Create Event</p>
			<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				{% include 'form_template.html'%}
				<div class="form-group">
					<div class="col-md-10">
						<button type="submit" class="btn btn-primary">Add Article</button>
					</div>
				</div>
			</form>
		</div>
	</div>
{% endblock %}
		

DragonFeedCode/articles/templates/details.html
{% extends 'layout.html'%}

{% block title %}<title>DragonFeed - {{ article.Title }} Details</title>{% endblock %}

{% block index.html%}
    <div class="container col-centered">
        <p class="text-center content-header">{{ article.Title }}</p>
        <br>
        <div class="row">
            <div class="card" style="width: 22rem; margin-left:200px;">
                <img src="{{ article.Flyer.url }}" class="card-img-top" alt=" {{ article.Title }} event">
            </div>
            <div class="col-md-5 col-md-offset-2">
                <br>
                <br>
                <br>
                <h5>More information here</h5>
                <p>Orginization: {{ article.Orginization }}</p>
                <p>Location: {{ article.Location }}</p>
                <p>Description: {{ article.Description }}</p>
                <p>Start Time: {{ article.Start }}</p>
                <p>End Time: {{ article.End }}</p>
                <p>More information about this event can be found
                     <a href="{{ article.Link }}" target="_blank">here</a>!</p>
            </div>
        </div>
    </div>
{% endblock %}

DragonFeedCode/articles/templates/form_template.html
{% load bootstrap %}
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger">{{ field.errors }}</span>
		</div>
		<div class="col-md-4">
			<div class="field">
				{{field|bootstrap}}
			</div>
		</div>
	</div>
{% endfor %}

DragonFeedCode/articles/templates/formalEvents.html
{% extends 'layout.html'%}
{% block index.html%}
<div class="container">
    {% if allArticles %}
    <p class="text-center content-header">Current Formal* Events</p> 
        <div class="card-deck ">
            {% for article in allArticles %}
                {% if article.Orginization %} 
                    <div class="card">
                        <a href="{% url 'article:details' article.id %}">
                            <img class="card-img-top" src="{{ article.Flyer.url}}" alt="Card image cap">
                        </a>
                        <div class="card-footer">
                            <small class="text-muted">Uploaded {{article.timestamp}}</small>
                        </div>
                    </div>  
                {% endif %} 
            {% endfor %} 
        </div> 
        <br>
        <h4>*A formal event is defined as an event held by a Dexel associated orginization.</h4> 
        {% else %}
        <div class="container">
            <h1>No Formal Events Yet</h1>
        </div> 
    {% endif %}
</div>
{% endblock %}

DragonFeedCode/articles/templates/index.html
{% extends 'layout.html'%}
{% block index.html%}
<div class="container">
    {% if allArticles %} 
        <p class="text-center content-header">Current Events</p>
        <div class="card-deck">
            {% for article in allArticles %}
                <div class="col-md-4">
                    <div class="card">
                        <a href="{% url 'article:details' article.id %}">
                            <img class="card-img-top" src="{{ article.Flyer.url}}" alt="Card image cap">
                        </a>
                        <br>
                        <div class="card-footer">
                            <small class="text-muted">Uploaded {{article.timestamp}}</small>
                        </div>
                    </div>
                    <br> 
                </div>          
            {% endfor %}
        </div>     
        {% else %}
            <h1>No Events Yet</h1>
    {% endif %}
</div>
{% endblock %}

DragonFeedCode/articles/templates/informalEvents.html
{% extends 'layout.html'%}
{% block index.html%}
<div class="container">
    {% if allArticles %}
    <p class="text-center content-header">Current Informal* Events</p> 
        <div class="card-deck ">
            {% for article in allArticles %}
                {% if not article.Orginization %} 
                    <div class="card">
                        <a href="{% url 'article:details' article.id %}">
                            <img class="card-img-top" src="{{ article.Flyer.url}}" alt="Card image cap">
                        </a>
                        <div class="card-footer">
                            <small class="text-muted">Uploaded {{article.timestamp}}</small>
                        </div>
                    </div>  
                {% endif %} 
            {% endfor %} 
        </div> 
        <br>
        <h4>*An informal event is defined as an event <span style="weight:bold;">not</span> 
            held by a Dexel associated orginization rather by a group of Drexel students.
        </h4> 
        {% else %}
        <div class="container">
            <h1>No Formal Events Yet</h1>
        </div> 
    {% endif %}
</div>
{% endblock %}

DragonFeedCode/articles/templates/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	{% block title %}<title>DragonFeed - New And Informal News</title>{% endblock %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Raleway:400,600" rel="stylesheet">

</head>

<body>
	<!-- Bootstarp navbar-->
	<nav class="navbar navbar-expand-md navbar-light nav-bar">
	  	<a class="navbar-brand" href="{% url 'article:index' %}">
			<img src="{% static 'images/DragonFeedSmall.png'%}" width="50" height="50" alt="DragonFeed">
		</a>
	  	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    	<span class="navbar-toggler-icon"></span>
	  	</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
		    <ul class="navbar-nav mr-auto">
				<a href="{% url 'article:formal' %}">
					<button class="nav-item btn my-2 my-sm-0 nav-bar-button-porperties">
						Formal Events
					</button>
				</a>		
				<a href="{% url 'article:informal' %}">
					<button class="nav-item btn my-2 my-sm-0 nav-bar-button-porperties">
						Informal Events
					</button>
				</a>
				<a href="{% url 'article:addevent' %}">
					<button class="nav-item btn my-2 my-sm-0 nav-bar-button-porperties">
						Add Article
					</button>
				</a>	
			</ul>
		    <ul class="navbar-nav ml-auto">
			    <form class="form-inline my-2 my-lg-0">
			      <input class="form-control mr-sm-2 nav-bar-input-porperties" type="search" class="search-nav" placeholder="Search by Tag" aria-label="Search">
			      <button class="btn my-2 my-sm-0 nav-bar-button-porperties" type="submit">Search</button>
			    </form>
			    <form class="form-inline my-2 my-lg-0">
					<button class="btn my-2 my-sm-0 nav-bar-button-porperties" type="submit">Sign Up</button>
				</form>
          	</ul>
		</div>
	</nav>
	<br>
	
		{% block index.html%}
		
		{% endblock %}

	<br>
</body>
<script type="text/javascript" href="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" href="{% static 'js/bootstrap.js' %}"></script>
<script type="text/javascript" href="{% static 'js/my.js' %}"></script>
</html>